### ISSUE TITLE
Client IP cannot be accessed from pods running in EKS

### ISSUE THREAD

**Issue by abelanger5** [porter-dev/porter#632]
# Location

- [ ] Browser
- [ ] CLI
- [X] API

# Details

In EKS, the internal IP address of the EC2 instance is set as the `$remote_addr` when forwarded from NGINX. From the NGINX ingress documentation (https://kubernetes.github.io/ingress-nginx/user-guide/miscellaneous/#source-ip-address), it states:
> If the ingress controller is running in AWS we need to use the VPC IPv4 CIDR.

The issue is that AWS is replacing the `X-Forwarded-For` header with the IP address of the internal EC2 instance. AWS can optionally prepend a proxy protocol header to the TCP data containing the source IP address, which NGINX doesn't pass to upstream services by default. 

# Suggested Fix

If you modify the Helm values directly from the Porter dashboard for the `nginx-ingress` chart, the following will configure everything correctly on the EKS side:

```yaml
controller:
  config:
    use-proxy-protocol: 'true'
  metrics:
    annotations:
      prometheus.io/port: '10254'
      prometheus.io/scrape: 'true'
    enabled: true
  podAnnotations:
    prometheus.io/port: '10254'
    prometheus.io/scrape: 'true'
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
```

If you are using a custom domain, this should be enough to get the client IP headers. However, when forwarded from a `*.porter.run` domain, the source IP is replaced with a Porter IP address, so there are still changes required at the server level.

**Comment by evantahler** [comment]
Trying out these changes resulted in lots of errors like:
```
2021/05/05 15:15:42 [error] 2987#2987: *12081097 broken header: "" while reading PROXY protocol, client: 10.0.5.109, server: 0.0.0.0:443
```

The original Helm chart that came with the `nginx-ingress` chart:

```
controller:
  metrics:
    annotations:
      prometheus.io/port: '10254'
      prometheus.io/scrape: 'true'
    enabled: true
  podAnnotations:
    prometheus.io/port: '10254'
    prometheus.io/scrape: 'true'
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
```

**Comment by abelanger5** [comment]
@evantahler my apologies, my specific version is using a classic load balancer instead of NLB, so the behavior may be different. I will have to test with the NLB and a custom domain. Did you try merging the `nlb-ip` annotation with the values that fixed it for me? For you, this would be:

```yaml
controller:
  config:
    use-proxy-protocol: 'true'
  metrics:
    annotations:
      prometheus.io/port: '10254'
      prometheus.io/scrape: 'true'
    enabled: true
  podAnnotations:
    prometheus.io/port: '10254'
    prometheus.io/scrape: 'true'
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
      service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
```
